# Generated by Django 4.2 on 2023-04-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
