# Generated by Django 4.2 on 2023-04-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_outbound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbound',
            old_name='inbound_date',
            new_name='outbound_date',
        ),
    ]
